clang-tidy: Relax -Werror for unused parameters
Auto-generated headers often include parameters required by templates
but unused in practice, triggering -Wunused-parameter and failing builds
under werror=true. Fixing these in generators is complex and low-value
compared to enabling clang-tidy now.

Use [[maybe_unused]] on unused parameters as a pragmatic workaround.
This keeps warnings visible, avoids manual edits to generated files,
and allows us to integrate clang-tidy.

Example of previous errors:
'''
./gen_serialization.hpp:5947:20: error: unused parameter 'a' [-Werror,-Wunused-parameter]
 5947 | void save(Archive& a,
      |                    ^
./gen_serialization.hpp:5948:96: error: unused parameter 'object' [-Werror,-Wunused-parameter]
 5948 |           const sdbusplus::xyz::openbmc_project::Inventory::Decorator::server::VoltageControl& object,
      |                                                                                                ^
./gen_serialization.hpp:5955:90: error: unused parameter 'object' [-Werror,-Wunused-parameter]
 5955 |           sdbusplus::xyz::openbmc_project::Inventory::Decorator::server::VoltageControl& object,
      |                                                                                          ^
./gen_serialization.hpp:6597:20: error: unused parameter 'a' [-Werror,-Wunused-parameter]
 6597 | void save(Archive& a,
      |                    ^
./gen_serialization.hpp:6598:80: error: unused parameter 'object' [-Werror,-Wunused-parameter]
 6598 |           const sdbusplus::xyz::openbmc_project::Inventory::Item::server::Bmc& object,
      |                                                                                ^
'''

Change-Id: I4441f0f3f3538b55c446d7c8441e6bdef4531c09
Signed-off-by: Jayanth Othayoth <ojayanth@gmail.com>