clang-tidy: delete default constructor
Default constructor was invalid for class semantics and caused
clang-tidy/Clang diagnostics. Mark the default constructor as
`=delete` to prevent accidental default construction and keep
-Werror builds green. No functional changes.

Fixed below errors
'''
../manager.hpp:53:5: error: explicitly defaulted move constructor is implicitly deleted [-Werror,-Wdefaulted-function-deleted]
   53 |     Manager(Manager&&) = default;
../manager.hpp:54:14: error: explicitly defaulted move assignment operator is implicitly deleted [-Werror,-Wdefaulted-function-deleted]
   54 |     Manager& operator=(Manager&&) = default;

Change-Id: Iaf1c39e91448b43a3f6c0149a71b58889d71195c
Signed-off-by: Jayanth Othayoth <ojayanth@gmail.com>